on: [push]

jobs:
  zstu-daily-report-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Check out
        id: report
        uses: actions/zstu-report-docker-action@v1
        with:
          username: '2019329600124'
          password: 'Chen2001'
          location: '浙江省 宁波市 慈溪市'
      - name: Get the return
        run: echo "The time was ${{ steps.report.outputs.result }}"
